version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ea-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ea_db
    ports:
      - "5436:5432"
    volumes:
      - ea-postgres:/var/lib/postgresql/data
    networks:
      - equipment-accounting

  backend:
    build: ./Equipment Accounting Backend
    container_name: ea-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ea_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: secret
    depends_on:
      - db
      - redis
      - keycloak
    networks:
      - equipment-accounting

  frontend:
    build: ./Equipment Accounting Frontend
    container_name: ea-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak
    networks:
      - equipment-accounting

  redis:
    image: redis:latest
    container_name: ea_redis
    ports:
      - "6379:6379"
    networks:
      - equipment-accounting

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ea-redis_insight
    ports:
      - "5540:5540"
    networks:
      - equipment-accounting
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: ea-keycloak
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/ea_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8082
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    networks:
      - equipment-accounting

networks:
  equipment-accounting:
    driver: bridge

volumes:
  ea-postgres:
  redis-insight:

