spring:
  application:
    name: Equipment Accounting Backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/equipment_accounting
          jwk-set-uri: http://keycloak:8080/realms/equipment_accounting/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://db:5432/ea_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.default_schema: backend
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG